createSQL:
  description: >
    Create a SQL query to fetch records from a MySQL database for user: {user}. Include user_name and kyc_compliant 
    columns in the SQL query.
  expected_output: >
    SQL query prefixed with "SQL Query:"
  agent: db_developer


queryDB:
  description: >
    Execute the SQL query against the MYSQL database. The response contains whether the user {user}
    is KYC compliant or not.
  expected_output: >
    True or False prefixed with "KYC compliance status: "
  agent: SQL_Sentinel

#reporting_task:
#  description: >
#    Review the context you got and expand each topic into a full section for a report.
#    Make sure the report is detailed and contains any and all relevant information.
#  expected_output: >
#    A fully fledged report with the main topics, each with a full section of information.
#    Formatted as markdown without '```'
#  agent: reporting_analyst
